# Generated by Django 4.2.7 on 2023-12-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barang', models.CharField(max_length=200)),
                ('publish', models.DateTimeField(verbose_name='tanggal beli')),
                ('harga', models.CharField(max_length=200)),
            ],
        ),
    ]
